default_language_version:
    python: python3.11

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.1
  hooks:

    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
      verbose: true # show the result of the linter in the terminal.



    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
      verbose: true # show the result of the linter in the terminal.